insert into district value(8162,'CENTRAL');
insert into district value(8175,'CRIME BRANCH');
insert into district value(8176,'DWARKA');
insert into district value(8168,'EAST');
insert into district value(8956,'EOW');
insert into district value(8169,'IGI AIRPORT');
insert into district value(8160,'METRO');
insert into district value(8165,'NEW DELHI');
insert into district value(8166,'NORTH');
insert into district value(8173,'NORTH EAST');
insert into district value(8172,'NORTH WEST');
insert into district value(8174,'OUTER DISTRICT');
insert into district value(8991,'OUTER NORTH');
insert into district value(8164,'RAILWAYS');
insert into district value(8959,'ROHINI');
insert into district value(8957,'SHAHDARA');
insert into district value(8167,'SOUTH');
insert into district value(8171,'SOUTH WEST');
insert into district value(8955,'SOUTH-EAST');
insert into district value(8954,'SPECIAL CELL');
insert into district value(8953,'SPECIAL POLICE UNIT FOR WOMEN &amp; CHILDREN');
insert into district value(8161,'VIGILANCE');
insert into district value(8170,'WEST');